language: ruby

sudo: required
cache: bundler

services:
 - mysql

dist: trusty

before_install:
  - jdk_switcher use openjdk8
  - ./.travis-install-dependencies.sh

before_script:
  - jdk_switcher use $JDK
  - bundle exec rake db:migrate

script: ./build.sh

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - RAILS_ENV=test MYSQL_PASSWORD='root' MYSQL_USER='root' JRUBY_OPTS='-J-Xmx1024m'

rvm:
  - jruby-9.1.14.0
